In [1]:
#Importing dependencies

import pandas as pd    #for data manipulation
import io    #for reading uploaded files stored in memory

In [2]:
#Upload mirdeep2 quantifier output files (.tabular)
#Each file = one sequencing sample; 20 control & 18 SCZ

from google.colab import files
uploaded = files.upload()

Saving SRR24055586.tabular to SRR24055586.tabular
Saving SRR24055587.tabular to SRR24055587.tabular
Saving SRR24055588.tabular to SRR24055588.tabular
Saving SRR24055589.tabular to SRR24055589.tabular
Saving SRR24055590.tabular to SRR24055590.tabular
Saving SRR24055591.tabular to SRR24055591.tabular
Saving SRR24055592.tabular to SRR24055592.tabular
Saving SRR24055593.tabular to SRR24055593.tabular
Saving SRR24055594.tabular to SRR24055594.tabular
Saving SRR24055595.tabular to SRR24055595.tabular
Saving SRR24055596.tabular to SRR24055596.tabular
Saving SRR24055597.tabular to SRR24055597.tabular
Saving SRR24055598.tabular to SRR24055598.tabular
Saving SRR24055599.tabular to SRR24055599.tabular
Saving SRR24055600.tabular to SRR24055600.tabular
Saving SRR24055601.tabular to SRR24055601.tabular
Saving SRR24055602.tabular to SRR24055602.tabular
Saving SRR24055603.tabular to SRR24055603.tabular
Saving SRR24055604.tabular to SRR24055604.tabular
Saving SRR24055605.tabular to SRR24055605.tabular
Saving SRR32768338.tabular to SRR32768338.tabular
Saving SRR32768339.tabular to SRR32768339.tabular
Saving SRR32768340.tabular to SRR32768340.tabular
Saving SRR32768341.tabular to SRR32768341.tabular
Saving SRR32768342.tabular to SRR32768342.tabular
Saving SRR32768343.tabular to SRR32768343.tabular
Saving SRR32768344.tabular to SRR32768344.tabular
Saving SRR32768345.tabular to SRR32768345.tabular
Saving SRR32768346.tabular to SRR32768346.tabular
Saving SRR32768347.tabular to SRR32768347.tabular
Saving SRR32768349.tabular to SRR32768349.tabular
Saving SRR32768351.tabular to SRR32768351.tabular
Saving SRR32768352.tabular to SRR32768352.tabular
Saving SRR32768353.tabular to SRR32768353.tabular
Saving SRR32768354.tabular to SRR32768354.tabular
Saving SRR32768355.tabular to SRR32768355.tabular
Saving SRR32768356.tabular to SRR32768356.tabular
Saving SRR32768357.tabular to SRR32768357.tabular

In [3]:
#empty list to store individual sample dataframe

dfs = []


# Loop thru uploaded files and extract miRNA and read_counts from each sample

for filename in uploaded.keys():

  df = pd.read_csv(io.BytesIO(uploaded[filename]),
                   sep ='\t')

# choose only these columns: '#miRNA', 'read_count'

  df = df[['#miRNA', 'read_count']]

#convert filename(SRR IDS) to column name for each sample:

  sample_name = filename.replace(".tabular", "")

  df.columns = ["miRNA" , sample_name]

#store processed dataframe for merging later

  dfs.append(df)

In [4]:
#sanity check for number of samples stored

len(dfs)

38

In [5]:
#Sanity check for change of column name

dfs[0].head()

             miRNA  SRR24055586
0    hsa-let-7a-5p         98.0
1    hsa-let-7a-3p          0.0
2    hsa-let-7a-5p        117.0
3  hsa-let-7a-2-3p          0.0
4    hsa-let-7a-5p         99.0

In [6]:
#set miRNA as index to align rows across samples

for i in range(len(dfs)):
  dfs[i] = dfs[i].set_index("miRNA")

In [7]:
dfs[0].head()

                 SRR24055586
miRNA
hsa-let-7a-5p           98.0
hsa-let-7a-3p            0.0
hsa-let-7a-5p          117.0
hsa-let-7a-2-3p          0.0
hsa-let-7a-5p           99.0

In [8]:
#merge all counts

count_matrix = pd.concat(dfs, axis = 1)

In [9]:
count_matrix.head()

,SRR24055586,SRR24055587,SRR24055588,SRR24055589,SRR24055590,SRR24055591,SRR24055592,SRR24055593,SRR24055594,SRR24055595,...,SRR32768346,SRR32768347,SRR32768349,SRR32768351,SRR32768352,SRR32768353,SRR32768354,SRR32768355,SRR32768356,SRR32768357
miRNA,,,,,,,,,,,,,,,,,,,,,
hsa-let-7a-5p,98.0,506.0,215.0,82.0,199.0,1299.0,1000.0,1276.0,380.0,484.0,...,39.0,38832.0,54258.0,165402.0,49027.0,4392.0,58868.0,6936.0,29403.0,33064.0
hsa-let-7a-3p,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,9.0,2.0,5.0,6.0,5.0,0.0,0.0,11.0,0.0
hsa-let-7a-5p,117.0,556.0,228.0,82.0,227.0,1498.0,1098.0,1534.0,435.0,588.0,...,42.0,38875.0,54328.0,165299.0,49097.0,4394.0,58910.0,6934.0,29462.0,33017.0
hsa-let-7a-2-3p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
hsa-let-7a-5p,99.0,506.0,215.0,82.0,199.0,1300.0,1006.0,1270.0,381.0,484.0,...,39.0,38793.0,54264.0,165108.0,49011.0,4380.0,58843.0,6933.0,29384.0,33005.0

In [10]:
# convert all count values to integer

count_matrix = count_matrix.astype(int)

In [11]:
#sanity check

count_matrix.dtypes

SRR24055586    int64
SRR24055587    int64
SRR24055588    int64
SRR24055589    int64
SRR24055590    int64
SRR24055591    int64
SRR24055592    int64
SRR24055593    int64
SRR24055594    int64
SRR24055595    int64
SRR24055596    int64
SRR24055597    int64
SRR24055598    int64
SRR24055599    int64
SRR24055600    int64
SRR24055601    int64
SRR24055602    int64
SRR24055603    int64
SRR24055604    int64
SRR24055605    int64
SRR32768338    int64
SRR32768339    int64
SRR32768340    int64
SRR32768341    int64
SRR32768342    int64
SRR32768343    int64
SRR32768344    int64
SRR32768345    int64
SRR32768346    int64
SRR32768347    int64
SRR32768349    int64
SRR32768351    int64
SRR32768352    int64
SRR32768353    int64
SRR32768354    int64
SRR32768355    int64
SRR32768356    int64
SRR32768357    int64
dtype: object

In [12]:
# Remove duplicate mirnas, and sum the duplicate values

count_matrix.index.duplicated().sum()

np.int64(232)

In [13]:
count_matrix = count_matrix.groupby(count_matrix.index).sum()

In [14]:
count_matrix.index.duplicated().sum()

np.int64(0)

In [18]:
# final rows and columns

count_matrix.shape
count_matrix.head(10)

,SRR24055586,SRR24055587,SRR24055588,SRR24055589,SRR24055590,SRR24055591,SRR24055592,SRR24055593,SRR24055594,SRR24055595,...,SRR32768346,SRR32768347,SRR32768349,SRR32768351,SRR32768352,SRR32768353,SRR32768354,SRR32768355,SRR32768356,SRR32768357
miRNA,,,,,,,,,,,,,,,,,,,,,
hsa-let-7a-2-3p,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hsa-let-7a-3p,0,0,0,0,0,2,0,0,0,0,...,0,18,4,10,12,10,0,0,22,0
hsa-let-7a-5p,314,1568,658,246,625,4097,3104,4080,1196,1556,...,120,116500,162850,495809,147135,13166,176621,20803,88249,99086
hsa-let-7b-3p,0,0,0,0,0,0,0,0,0,0,...,0,2,4,11,0,0,0,0,0,0
hsa-let-7b-5p,176,1441,558,290,909,2070,2000,846,436,441,...,15,7506,21631,41041,17385,1526,17934,1760,6329,6990
hsa-let-7c-3p,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hsa-let-7c-5p,26,73,29,23,42,301,142,171,53,79,...,11,519,770,1737,574,124,544,123,505,495
hsa-let-7d-3p,3,4,1,5,1,0,2,14,0,2,...,1,146,83,707,188,19,108,11,88,115
hsa-let-7d-5p,8,62,18,18,19,120,133,160,27,48,...,1,1131,1531,5885,1072,120,1472,135,760,836
hsa-let-7e-3p,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
#Check the totla number of counts gennerated in each sample

count_matrix.sum()

SRR24055586      26015
SRR24055587     160755
SRR24055588      53350
SRR24055589      14793
SRR24055590      79293
SRR24055591     292408
SRR24055592     154416
SRR24055593     118175
SRR24055594      32448
SRR24055595      33076
SRR24055596     439101
SRR24055597      60441
SRR24055598      44873
SRR24055599     131350
SRR24055600      95483
SRR24055601     257212
SRR24055602      37057
SRR24055603     131236
SRR24055604      95202
SRR24055605    1061541
SRR32768338     371224
SRR32768339     749616
SRR32768340     507294
SRR32768341     373376
SRR32768342    1452741
SRR32768343     292691
SRR32768344     211966
SRR32768345     665390
SRR32768346       1174
SRR32768347     809945
SRR32768349    1164219
SRR32768351    3346217
SRR32768352    1081756
SRR32768353     104398
SRR32768354    1163701
SRR32768355     134709
SRR32768356     562657
SRR32768357     661607
dtype: int64

In [20]:
 #save as csv

 count_matrix.to_csv("miRNA_countmatrix.csv")